name: Safari e2e tests
on: workflow_dispatch
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        uses: cypress-io/github-action@v6
        with:
          # Install WebKit browser dependencies
          build: npx playwright install-deps webkit
          runTests: false
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
          browser: webkit
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()  # This step only runs if there's a failure
        with:
          name: cypress-screenshots
          path: cypress/screenshots